"""
 - FAÇA UM PROGRAMA QUE POSSUA UMA LISTA DENOMINADA A QUE ARMAZENE 6  NUMEROS INTEIROS. O PROGRAMA DEVE EXECUTAR OS SEGUINTES PASSO
- ATRIBUA OS SEGUINTES VALORES A ESSA LISTA 1, 0, 5, -2, -5, 7.
- ARMAZENE EM UMA VARIAVEL INTERIRA A SOMA ENTRE OS VALORES DAS POSIÇÕES A[0], A[1] E A[5] DA LISTA E MOSTRE NA TELA ESTA SOMA
- MODIFIQUE A LISTA NA POSIÇÃO  5, ATRIBUINDO A ESTA POSIÇAO  O VALOR 100
- MOSTRE NA TELA CADA VALOR DA LISTA A, UM EM CADA LINHA
"""
"""maneira feita pelo professor """

A = [1, 0, 5, -2, -5, 7]

soma = A[0] + A[1] + A[5]
print(soma)

A[5] = 100
print(A)